kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.deployment.name }}-service
  labels:
    app: {{ .Values.deployment.name }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  selector:
    app: {{ .Values.deployment.name }}
